site_name: Maria Nadeem's AI Innovations
site_description: A showcase of my data science and AI projects
site_author: Maria Nadeem

nav:
  - Home: index.md
  - About: about.md
  - Projects: projects.md
  - Skills: skills.md
  - Certifications: certifications.md
  - Resume: resume.md
  - Experience: experience.md
  - Awards: achievements.md

theme:
  name: cinder
  palette:
    primary: 'indigo'
    accent: 'blue'
  logo: images/logo.png
  favicon: favicon.ico

extra_css:
  - stylesheets/custom.css

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/js/all.min.js
  - javascripts/custom.js

extra:
  favicon: favicon.ico

markdown_extensions:
  - admonition
  - footnotes
  - toc:
      permalink: true

plugins:
  - search

edit_uri: null